version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
            
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py pylint --errors-only
            - pylint $CODEBUILD_SRC_DIR/demoproj/*.py
            
artifacts:
    files:
        - '**/*'